# Autogenerated by nbdev

d = { 'settings': { 'branch': 'develop',
                'doc_baseurl': '/muzero',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/muzero',
                'lib_path': 'muzero'},
  'syms': {'muzero.core': {'muzero.core.foo': ('core.html#foo', 'muzero/core.py')}}}
