# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_muzero.ipynb.

# %% auto 0
__all__ = ['MuzeroConfig']

# %% ../nbs/13_muzero.ipynb 10
from dataclasses import dataclass

# %% ../nbs/13_muzero.ipynb 11
@dataclass
class MuzeroConfig:
    action_space: int
