# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_muzero.ipynb.

# %% auto 0
__all__ = ['MuzeroConfig']

# %% ../nbs/13_muzero.ipynb 8
from dataclasses import dataclass

from .nn import RepresentationNetwork, DynamicsNetwork, PredictionNetwork

# %% ../nbs/13_muzero.ipynb 9
@dataclass
class MuzeroConfig:
    action_space: int
