# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_nn.ipynb.

# %% auto 0
__all__ = ['RepresentationNetwork', 'DynamicNetwork']

# %% ../nbs/01_nn.ipynb 3
import torch
from torch import nn
import torch.nn.functional as F

# %% ../nbs/01_nn.ipynb 6
class RepresentationNetwork(nn.Module):
    def __init__(self):
        super().__init__()

# %% ../nbs/01_nn.ipynb 8
class DynamicNetwork(nn.Module):
    def __init__(self):
        super().__init__()
