# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_replay_buffer.ipynb.

# %% auto 0
__all__ = ['MuzeroConfig', 'ReplayBuffer', 'SharedStorage']

# %% ../nbs/08_replay_buffer.ipynb 4
from dataclasses import dataclass

from torch import nn

# %% ../nbs/08_replay_buffer.ipynb 5
@dataclass
class MuzeroConfig:
    action_space: int = 1

# %% ../nbs/08_replay_buffer.ipynb 6
class ReplayBuffer:
    def __init__(self, config: int = MuzeroConfig()):
        self.window_size = config.window_size
        self.batch_size = config.batch_size

# %% ../nbs/08_replay_buffer.ipynb 7
class SharedStorage:
    pass
